### ISSUE TITLE
SIGSEGV  running plan for DR-02011964

### ISSUE THREAD

**Issue by kaerumy** [Sinar/go-pardocs#4]
[DR-02011964.pdf](https://github.com/Sinar/go-pardocs/files/3368142/DR-02011964.pdf)

``` panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x6e0e0a]

goroutine 1 [running]:
github.com/Sinar/go-pardocs/internal/hansard.(*HansardDocument).Finalize(...)
	/home/kaeru/dev/go/src/github.com/Sinar/go-pardocs/internal/hansard/hansard.go:208
github.com/Sinar/go-pardocs.(*ParliamentDocs).Plan(0xc000531e08)
	/home/kaeru/dev/go/src/github.com/Sinar/go-pardocs/pardocs.go:64 +0x30a
main.(*planCmd).Execute(0xc00008abd0, 0x7f7c60, 0xc00009c010, 0xc0000a2480, 0x0, 0x0, 0x0, 0xc000088650)
	/home/kaeru/dev/go/src/github.com/Sinar/go-pardocs/cmd/go-pardocs/main.go:123 +0x477
github.com/Sinar/go-pardocs/vendor/github.com/google/subcommands.(*Commander).Execute(0xc000121340, 0x7f7c60, 0xc00009c010, 0x0, 0x0, 0x0, 0x6e3e2d)
	/home/kaeru/dev/go/src/github.com/Sinar/go-pardocs/vendor/github.com/google/subcommands/subcommands.go:142 +0x2fb
github.com/Sinar/go-pardocs/vendor/github.com/google/subcommands.Execute(...)
	/home/kaeru/dev/go/src/github.com/Sinar/go-pardocs/vendor/github.com/google/subcommands/subcommands.go:420
main.main()
	/home/kaeru/dev/go/src/github.com/Sinar/go-pardocs/cmd/go-pardocs/main.go:29 +0x20f
```

**Comment by leowmjw** [comment]
Reviewed PDF; it is not from the modern parliament format.

Current planner expects to find a variation of "Soalan" near the top of the page to determine the boundary.  

This case will need to be a different type to be implemented; mark this as an enhancement for a new type.

**Comment by leowmjw** [comment]
PR from the lib used might be useful in splitting the Hansard per column
--> https://github.com/ledongthuc/pdf/pull/9/files
